### ISSUE TITLE
Open a new repo to backup a copy of his videos

### ISSUE THREAD

**Issue by embed-net** [jesuswordsonly/jesuswordsonly.github.io#7]
If you don't have  all of your videos from YouCensor backed up, you might want to open a repo and back them up to the repo.

I saw some on archive.org but it looks like it's sporadic.

It's open season on Christians worldwide and you can get flushed from YouGone in a heartbeat.

**Comment by embed-net** [comment]
PS: do you really want to make them at 1920 dpi resolution? You have a lot of them so it uses a lot of space and increases download times.

**Comment by jesuswordsonly** [comment]
backing up Douglas' videos sounds great! i was thinking they should be backed up and available on alternative sites like rumble and others. i agree with you 100%. if you want to contribute somehow i think that would be appreciated. there are tools to download youtube videos, and you could download in 720p or even 480p if it doesn't have small text.

as far as the sheer amount of content, i like it. no, i don't watch every video. but i think the topic is in dire need of content in general.

**Comment by embed-net** [comment]
OK great. Could you open a REPO and have a youtube subdirectory in case there are other video sites later.

I have >200 downloaded from youtube and many resized by ffmpeg to cut them in half. If you open a repo I can add a PR and all you have to do is acccept the PR. Maybe I'll do one PR per video for tracking?

**Comment by jesuswordsonly** [comment]
hmm.. it sounds easy, but might not be a best practice, as mentioned in #1 .. maybe rumble or another video hosting site would be best.. it gets me thinking.. a new site should have all the videos, but i don't know if we want to pay for hosting so many GB of video content. maybe. but many people just embed using youtube. but youtube is unreliable, so i would embed using rumble or something else. honestly i don't trust any site, at all really, and i would backup locally.

since i will likely be developing a new site soon, i should check with douglas to see if he still has all his original content at full quality, offline.

i'm not stopping you from uploading, distributing, etc. if you think it's a good idea, feel free to fork this repo, and upload the videos in a new folder, for example.

**Comment by embed-net** [comment]
You're probably right - github is not the best place for it. I have only some of his videos and it's >20G! Although I share your scepticism, but I think archive.org is OK (while still it breathes).

I'll see if I can script uploading to it and if so, we could link from the site to videos that are there.

PS: I still want to archive on github in a parallel repo the PDFs referred to by the site...

**Comment by embed-net** [comment]
I'll let you or Doug do this, as although I can script this, uploads are throttled with liimits on uploads per hour and it would take  forever to do 25G,
